### ISSUE TITLE
error when I try to upload file?

### ISSUE THREAD

**Issue by lpt2007** [soif/EspBuddy#18]
> 22:39:27 [DEBUG]: Options: {'esp_ip': '192.168.2.2', 'host_port': 43449, 'image': '/var/www/html/EspBuddy/firmwares/ESPEasyUploader.OTA.1m128.esp8266.bin', 'host_ip': '0.0.0.0', 'auth': '', 'esp_port': 8266, 'spiffs': False, 'debug': True, 'progress': True}
22:39:27 [INFO]: Starting on 0.0.0.0:43449
22:39:27 [INFO]: Upload size: 288048
22:39:27 [INFO]: Sending invitation to: 192.168.2.2
22:39:37 [ERROR]: No Answer

FATAL ERROR: First Upload Failed !!!

I can ping device ip with no problem? Why device is no answering?

**Comment by soif** [comment]
Is OTA enabled in ESPeasy advanced settings ?

**Comment by lpt2007** [comment]
Hi,

I don't have OTA in advance settings only this:


Subscribe Template: |  
-- | --
Publish Template: |  
Message Delay (ms): |  
Fixed IP Octet: |  
Use NTP: |  
NTP Hostname: |  
Timezone Offset: (Minutes) |  
DST: |  
Syslog IP: |  
Syslog Level: |  
UDP port: |  
Enable Serial port: |  
Serial log Level: |  
Web log Level: |  
Baud Rate: |  
WD I2C Address: |  
Custom CSS: |  
Use SSDP: |  
Connection Failure Threshold: |  
Rules: |  

I2C ClockStretchLimit: |  
Global Sync: |

**Comment by soif** [comment]
you have to build a v2.0 firmware, with OTA enabled (FEATURE_ARDUINO_OTA)

**Comment by lpt2007** [comment]
How?

My firmware version is:

Build: | 120
-- | --
Core Version: | 2_3_0

**Comment by soif** [comment]
it must be build with [**FEATURE_ARDUINO_OTA**](https://github.com/letscontrolit/ESPEasy/blob/mega/src/ESPEasy-Globals.h#L122) defined, _which is NOT defined by default_ !
Did you do it?

**Comment by lpt2007** [comment]
I already do manual ota upgrade to 2.3.0 build 120. I just wana upgrade espeasy to mega but file is to big. Can I do manual upgrade in two steps first "ESPEasyUploader.OTA.1m128.esp8266.bin" then normal firmwarea?

**Comment by Andrey2509** [comment]
Size of the first flash image is too big (288 kb). I have only 212 kb free.

```
Firmware
--
Build | 20101  - Mega (ESP82xx Core 2_4_0)
GIT version | mega-20180421
Plugins | 47 [Normal]
Build Md5 | a826642d5534b9f99d7f3d9f4a1c14d1
Md5 check | passed.
Build time | Apr 21 2018 02:01:55
Binary filename | firmware.bin
ESP board
ESP Chip ID | 916988 (0xDFDFC)
ESP Chip Freq: | 80 MHz
Storage
Flash Chip ID | Vendor: 0x5E Device: 0x4014
Flash Chip Real Size: | 1024 kB
Flash IDE Size: | 1024 kB
Flash IDE speed: | 40 MHz
Flash IDE mode: | DOUT
Flash Writes | 0 daily / 2 boot
Sketch Size | 662 kB (212 kB free)

```
