### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by ascillato** [soif/EspBuddy#2]
Hi,

How I can run espbuddy.php ?

Which software I need ?

Thanks

**Comment by soif** [comment]
You must have php (v5+) installed.
- Ie on a debian/ubuntu/rasbian : `apt-get install php5-cli`
- on recent OSX it should be already installed
- on Windows you need a php.exe... Google is your friend :-)

**Comment by ascillato** [comment]
Thanks!

**Comment by soif** [comment]
you're welcome
