### ISSUE TITLE
Flashing a custom Firmware to Sonoff DIY devices, from the factory firmware 

### ISSUE THREAD

**Issue by soif** [soif/EspBuddy#20]
I've tested all "**sonodiy**" actions, except the 'flash' command. _Because I currently have only one device, and flashing it can not be reversed to the factory firmware, so I would'nt be able to make further tests._

It should work asis, if the device accept an external URL, as the default Tasmota one currently  configured in the config-sample.php file.

If it fails, it might be necessary to download the firmware directly to a local web server, and then change the URL according to the new location. 
* Try with a local hostname, ie: 
`http://mycomputer.local/firmare.bin`

* or even directly with an IP address, ie:
`http://192.168.0.123/firmare.bin`

I would appreciate if you could **PLEASE report** if it works correcly and what were the exact steps that you tried.

Thank you

**Comment by soif** [comment]
as I feared, the ota_flash endpoint only accepts a local URL ( on the LAN), and silently ignore externals urls.
So first download the firmware to a local webserver, and use this URL to flash!

**Comment by soif** [comment]
use the latest 2.05b2 version
`espbuddy.php self update 2.05b2`

Then try adding the -P Option at the end of the flash command, and please report if it work 🍺

**Comment by senadaruc** [comment]
Hi,

Thanks for the tool but even with OTA unlock successful message I cant flash my device?

<img width="664" alt="Screenshot 2020-04-12 at 11 34 52" src="https://user-images.githubusercontent.com/14252382/79065574-b4a52980-7cb1-11ea-9065-6fb10477cddc.png">


Any help please?

Thanks,

**Comment by soif** [comment]
it means OTA has NOT been unlocked (while the device doesnt first report any error) , 

try to reboot the device, and send the unlock command again.

You can check if if has been really unlocked, using the _sonodiy info_ command.

 If it still failed, it might be the Sonof factory version which need to be updated first, or may be they changed the way the unlock command work in recent firmwares. 
I dont know, and can not help anymore. You'll have to investigate

If you make any progress, please be kind to report it here to help others, by opening a NEW issue, regarding this specific topic, or even better, push a PR.

**Comment by mikelgrant** [comment]
senadaruc - did you ever get your Sonoff to flash?  I'm having the same problem with a Sonoff mini r2.
